name: flat
description: >-
  0 dependency package to convert a nested Map and flatten it into a single depth Map,
  and recover it later. Based on Node.js `flat` package.

homepage: https://github.com/danilofuchs/flat
repository: https://github.com/danilofuchs/flat

version: 0.5.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.7

license: MIT
