name: flat
description: Take a nested Map and flatten it with delimited keys.
homepage: https://github.com/danilofuchs/flat
repository: https://github.com/danilofuchs/flat

version: 0.1.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.12.0

license: MIT
