name: flat
description: >-
  A simple, no dependency 🚀 way to take a nested Map and flatten it into a single depth Map.
  Based on Node.js `flat` package.

homepage: https://github.com/danilofuchs/flat
repository: https://github.com/danilofuchs/flat

version: 0.1.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.12.0

license: MIT
